services:
  db:
    container_name: db-barbershop-app
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: barbershop-app
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barbershop-app-backend

  redis:
    container_name: redis-barbershop-app
    image: redis:5.0
    restart: always
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - barbershop-app-backend

volumes:
  postgres_data:
  redis_data:

networks:
  barbershop-app-backend: